/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 10 00:23:09 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;
import tutorial.TwoStacks;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TwoStacks_ESTest extends TwoStacks_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TwoStacks twoStacks0 = new TwoStacks(2893);
      // Undeclared exception!
      try { 
        twoStacks0.pop2();
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TwoStacks twoStacks0 = new TwoStacks(1675);
      twoStacks0.push1(1675);
      int int0 = twoStacks0.pop1();
      assertEquals(1675, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TwoStacks twoStacks0 = new TwoStacks(0);
      // Undeclared exception!
      try { 
        twoStacks0.pop1();
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TwoStacks twoStacks0 = new TwoStacks(1);
      twoStacks0.push2(1);
      twoStacks0.pop2();
      twoStacks0.push1(0);
      // Undeclared exception!
      try { 
        twoStacks0.push2((-2279));
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TwoStacks twoStacks0 = new TwoStacks(1);
      twoStacks0.push2((-1));
      // Undeclared exception!
      try { 
        twoStacks0.push1((-3523));
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }
}
